version = 1

[global]
dll = "/home/bartek/.local/share/Steam/Lossless Scaling/Lossless.dll"

[[game]]
exe = "pascube"
dll = "/home/bartek/.local/share/Steam/Lossless Scaling/Lossless.dll"
multiplier = 2
flow_scale = 1.00
performance_mode = true
hdr_mode = false
legacy = true
experimental_present_mode = "fifo"

[[game]]
exe = "vkcube"
dll = "/home/bartek/.local/share/Steam/Lossless Scaling/Lossless.dll"
multiplier = 2
flow_scale = 1.00
performance_mode = true
hdr_mode = false
legacy = true
experimental_present_mode = "fifo"
