version = 1

[global]
dll = "~/.local/share/Steam/Lossless Scaling/Lossless.dll"

[[game]]
exe = "user"
multiplier = 3
flow_scale = 0.6
performance_mode = true
hdr_mode = false
experimental_present_mode = "fifo"
